#!/usr/bin/env python

import os

from skyhookdm.util import ArgparseBuilder
from skyhookdm.dataformats import SkyhookFileReader

# ------------------------------
# Parse command-line arguments first
parsed_args, parsed_extra_args = (
    ArgparseBuilder.with_description('Program for parsing data from binary arrow files')
                   .add_input_file_arg(
                         required=True
                        ,help_str='Path to arrow file (assumed to be gene expression)'
                    )
                   .parse_args()
)

# ------------------------------
if __name__ == '__main__':
    if os.path.isfile(parsed_args.input_file):
        data_table = SkyhookFileReader.read_data_file_as_arrow_table(parsed_args.input_file)

        print(data_table.schema)
        print(data_table.to_pandas())
